
language: objective-c
osx_image: xcode8.2

install: pod repo update; pod install

env:
  global:
    - WORKSPACE=PopcornTime.xcworkspace
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -workspace "$WORKSPACE" -scheme "PopcornTimetvOS" -sdk appletvsimulator10.1 -configuration Release | xcpretty -c;
  - xcodebuild -workspace "$WORKSPACE" -scheme "PopcornTimeiOS" -sdk iphonesimulator10.2 -configuration Release | xcpretty -c;
